In [4]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [5]:
reviews = ["nice food",
           "amazing restaurant",
           "too good",
           "just love it!",
           "will go again",
           "horrible food",
           "never go there",
           "poor service",
           "poor quality",
           "needs improvement"
           ]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
one_hot("amazing restaurant", 30)

[6, 2]

In [8]:
vocab_size = 30

encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[27, 11],
 [6, 2],
 [6, 17],
 [28, 4, 4],
 [19, 1, 1],
 [26, 11],
 [3, 1, 11],
 [17, 4],
 [17, 12],
 [10, 17]]

In [10]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[27, 11,  0],
       [ 6,  2,  0],
       [ 6, 17,  0],
       [28,  4,  4],
       [19,  1,  1],
       [26, 11,  0],
       [ 3,  1, 11],
       [17,  4,  0],
       [17, 12,  0],
       [10, 17,  0]], dtype=int32)

In [13]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

d:\Work\On\.PRACTISE\Learn\deep-learning-with-Tensorflow\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
X = padded_reviews
y = sentiment

In [15]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.fit(X, y, epochs=5, verbose=0)

In [17]:
loss, accuracy = model.evaluate(X, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.7000 - loss: 0.6824


In [19]:
weights = model.get_layer("embedding").get_weights()[0]
len(weights)

30

In [20]:
weights[11]

array([ 0.0175349 , -0.0283742 ,  0.04180084, -0.01840991], dtype=float32)

In [21]:
weights[3]

array([-0.00983449, -0.05344855, -0.01453061, -0.04777157], dtype=float32)